---
apiVersion: k0rdent.mirantis.com/v1alpha1
kind: ClusterTemplate
metadata:
  name: kubevirt-standalone-cp-0-2-1
  namespace: {{ .Values.config.namespace | default .Release.Namespace | trunc 63 }}
spec:
  helm:
    chartSpec:
      chart: kubevirt-standalone-cp
      version: 0.2.1
      interval: 10m0s
      sourceRef:
        kind: HelmRepository
        name: oot-repo
