---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: oot-repo
  namespace: {{ .Values.config.namespace | default .Release.Namespace | trunc 63 }}
  labels:
    k0rdent.mirantis.com/managed: "true"
spec:
  type: oci
  url: 'oci://ghcr.io/k0rdent-oot/oot/charts'
  interval: 10m0s
